window.RESTAURANT2_OWNER_CONFIG = {
  // Edit this file to manage owner-facing menu data in one place.
  defaultBusinessLocationId: 'default',
  businessLocations: {
    default: {
      id: 'default',
      label: 'John Doe | 123 Placeholder Ave | Sampletown, NY 10000',
      name: 'John Doe',
      address: '123 Placeholder Ave',
      cityStateZip: 'Sampletown, NY 10000',
      phone: '(315) 555-0101'
    }
  },
  sectionLabels: {
    pizza: 'Pizza',
    burger: 'Burger',
    calzone: 'Calzone',
    chicken_wings: 'Chicken Wings',
    salad: 'Salad',
    dinner: 'Dinner',
    sub: 'Sub',
    wrap: 'Wrap',
    sauces: 'Sauces',
    order: 'Order'
  },
  pizzaSizeLabels: {
    personal_pan: 'Personal Pan',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    sheet: 'Sheet',
    slices: 'Slices'
  },
  menuSections: {
    burger: {
      ingredients: [
        { value: 'bacon', label: 'Bacon' },
        { value: 'bbq_sauce', label: 'BBQ Sauce' },
        { value: 'bun', label: 'Bun', required: true },
        { value: 'cheese', label: 'Cheese' },
        { value: 'honey_mustard', label: 'Honey Mustard' },
        { value: 'hot_sauce', label: 'Hot Sauce' },
        { value: 'jalapenos', label: 'Jalapeños' },
        { value: 'ketchup', label: 'Ketchup' },
        { value: 'lettuce', label: 'Lettuce' },
        { value: 'mayonnaise', label: 'Mayonnaise' },
        { value: 'medium_well', label: 'Medium-Well' },
        { value: 'mild_sauce', label: 'Mild Sauce' },
        { value: 'mustard', label: 'Mustard' },
        { value: 'mushrooms', label: 'Mushrooms' },
        { value: 'olives', label: 'Olives' },
        { value: 'onion', label: 'Onion' },
        { value: 'patty', label: 'Patty', required: true },
        { value: 'pickles', label: 'Pickles' },
        { value: 'ranch', label: 'Ranch' },
        { value: 'rare', label: 'Rare' },
        { value: 'relish', label: 'Relish' },
        { value: 'tartar_sauce', label: 'Tartar Sauce' },
        { value: 'tomatoes', label: 'Tomatoes' },
        { value: 'well_done', label: 'Well-Done' }
      ]
    },
    calzone: {
      ingredients: [
        {
          value: 'regular_dough',
          label: 'Dough',
          required: true,
          noQty: true,
          inputId: 'calzone-dough-checkbox',
          selectId: 'calzone-dough-select',
          selectAriaLabel: 'Choose calzone dough',
          options: [
            { value: 'regular_dough', label: 'Regular' },
            { value: 'wheat_free_dough', label: 'Wheat Free' },
            { value: 'gluten_free_dough', label: 'Gluten Free' }
          ]
        },
        { value: 'american_cheese', label: 'American Cheese' },
        { value: 'bacon_bits', label: 'Bacon Bits' },
        { value: 'banana_peppers', label: 'Banana Peppers' },
        { value: 'black_pepper', label: 'Black Pepper' },
        { value: 'broccoli', label: 'Broccoli' },
        { value: 'cheddar_cheese', label: 'Cheddar Cheese' },
        { value: 'chicken', label: 'Grilled Chicken Strips' },
        { value: 'eggplant', label: 'Eggplant' },
        { value: 'feta_cheese', label: 'Feta Cheese' },
        { value: 'garlic_powder', label: 'Garlic Powder' },
        { value: 'grated_parmesan_or_pecorino', label: 'Grated Parmesan or Pecorino' },
        { value: 'greens', label: 'Greens' },
        { value: 'green_peppers', label: 'Green Peppers' },
        { value: 'ham', label: 'Ham' },
        { value: 'hot_peppers', label: 'Hot Peppers' },
        { value: 'jalapenos', label: 'Jalapeño' },
        { value: 'italian_seasoning', label: 'Italian Seasoning' },
        { value: 'meatballs', label: 'Meatballs' },
        { value: 'mushrooms', label: 'Mushrooms' },
        { value: 'olive_oil', label: 'Olive Oil' },
        { value: 'onion', label: 'Onion' },
        { value: 'pepperoni', label: 'Pepperoni' },
        { value: 'pineapple', label: 'Pineapple' },
        { value: 'ricotta_cheese', label: 'Ricotta Cheese' },
        { value: 'roasted_red_peppers', label: 'Roasted Red Peppers' },
        { value: 'salami', label: 'Salami' },
        { value: 'sausage', label: 'Sausage' },
        { value: 'salt', label: 'Salt' },
        { value: 'shredded_mozzarella', label: 'Shredded Mozzarella' },
        { value: 'spinach', label: 'Spinach' },
        { value: 'steak', label: 'Steak' },
        { value: 'swiss_cheese', label: 'Swiss Cheese' },
        { value: 'tomatoes', label: 'Tomatoes' }
      ]
    },
    chicken_wings: {
      ingredients: [
        { value: 'bbq_sauce', label: 'BBQ Sauce' },
        { value: 'butter_sauce', label: 'Butter Sauce' },
        { value: 'garlic', label: 'Garlic' },
        { value: 'honey', label: 'Honey' },
        { value: 'hot_and_spicy_barbecue_sauce', label: 'Hot and Spicy Barbecue Sauce' },
        { value: 'hot_sauce', label: 'Hot Sauce' },
        { value: 'medium_sauce', label: 'Medium Sauce' },
        { value: 'mild_sauce', label: 'Mild Sauce' },
        { value: 'mustard', label: 'Mustard' },
        { value: 'plain', label: 'Plain', required: true },
        { value: 'extra_hot_sauce', label: 'Extra Hot Sauce' },
        { value: 'spicy_garlic_parm_sauce', label: 'Spicy Garlic Parm Sauce' }
      ]
    },
    dinner: {
      ingredients: [
        { value: 'baked_ziti', label: 'Baked Ziti' },
        { value: 'chicken_parmigiana', label: 'Chicken Parmigiana' },
        { value: 'chicken_riggies', label: 'Chicken Riggies' },
        { value: 'house_italian_dressing', label: 'House Italian Dressing' },
        { value: 'lasagna', label: 'Lasagna' },
        { value: 'manicotti', label: 'Manicotti' },
        { value: 'spaghetti', label: 'Spaghetti' },
        { value: 'stuffed_shells', label: 'Stuffed Shells' },
        { value: 'vodka_riggies', label: 'Vodka Riggies' }
      ]
    },
    pizza: {
      pizzaSizes: ['personal_pan', 'small', 'medium', 'large', 'sheet', 'slices'],
      ingredients: [
        {
          value: 'regular_dough',
          label: 'Dough',
          required: true,
          noQty: true,
          inputId: 'pizza-dough-checkbox',
          selectId: 'pizza-dough-select',
          selectAriaLabel: 'Choose pizza dough',
          options: [
            { value: 'regular_dough', label: 'Regular' },
            { value: 'wheat_free_dough', label: 'Wheat Free' },
            { value: 'gluten_free_dough', label: 'Gluten Free' }
          ]
        },
        { value: 'bacon', label: 'Bacon' },
        { value: 'boneless_chicken_wings', label: 'Boneless Chicken Wings' },
        { value: 'broccoli', label: 'Broccoli' },
        { value: 'chicken', label: 'Grilled Chicken Strips' },
        { value: 'cheese', label: 'Cheese' },
        { value: 'cherry_peppers', label: 'Cherry Peppers' },
        { value: 'feta_cheese', label: 'Feta Cheese' },
        { value: 'garlic', label: 'Garlic' },
        { value: 'green_peppers', label: 'Green Peppers' },
        { value: 'ham', label: 'Ham' },
        { value: 'jalapenos', label: 'Jalapeños' },
        { value: 'lettuce', label: 'Lettuce' },
        { value: 'meatballs', label: 'Meatballs' },
        { value: 'mild_sauce', label: 'Mild Sauce' },
        { value: 'mushrooms', label: 'Mushrooms' },
        { value: 'olives', label: 'Olives' },
        { value: 'onion', label: 'Onion' },
        { value: 'pepperoni', label: 'Pepperoni' },
        { value: 'pickles', label: 'Pickles' },
        { value: 'pineapple', label: 'Pineapples' },
        { value: 'ranch', label: 'Ranch' },
        { value: 'ricotta_cheese', label: 'Ricotta Cheese' },
        { value: 'roasted_peppers', label: 'Roasted Peppers' },
        { value: 'sausage', label: 'Sausage' },
        { value: 'spinach', label: 'Spinach' },
        { value: 'thin_crust', label: 'Thin Crust' },
        { value: 'tomatoes', label: 'Tomatoes' },
        { value: 'tomato_sauce', label: 'Tomato Sauce', required: true },
        { value: 'well_done', label: 'Well-Done' }
      ]
    },
    salad: {
      ingredients: [
        { value: 'banana_peppers', label: 'Banana Peppers' },
        { value: 'croutons', label: 'Croutons' },
        { value: 'cucumbers', label: 'Cucumbers' },
        { value: 'green_peppers', label: 'Green Peppers' },
        { value: 'ham', label: 'Ham' },
        { value: 'italian_dressing', label: 'Italian Dressing' },
        { value: 'olives', label: 'Olives' },
        { value: 'provolone_cheese', label: 'Provolone Cheese' },
        { value: 'red_onion', label: 'Red Onion' },
        { value: 'red_peppers', label: 'Red Peppers' },
        { value: 'salami', label: 'Salami' },
        { value: 'tomato', label: 'Tomato' }
      ]
    },
    sauces: {
      ingredients: [
        { value: 'bbq', label: 'BBQ' },
        { value: 'butter_milk_ranch', label: 'Butter Milk Ranch' },
        { value: 'honey_bbq', label: 'Honey BBQ' },
        { value: 'honey_mustard', label: 'Honey Mustard' },
        { value: 'mayonnaise', label: 'Mayonnaise' },
        { value: 'mustard', label: 'Mustard' },
        { value: 'ranch', label: 'Ranch' }
      ]
    },
    sub: {
      ingredients: [
        { value: 'bacon', label: 'Bacon' },
        { value: 'bologna', label: 'Bologna' },
        { value: 'buffalo_sauce', label: 'Buffalo Sauce' },
        {
          value: 'white',
          label: 'Bread',
          required: true,
          noQty: true,
          inputId: 'sub-bread-checkbox',
          selectId: 'sub-bread-select',
          selectAriaLabel: 'Choose bread',
          options: [
            { value: 'white', label: 'White' },
            { value: 'wheat', label: 'Wheat' },
            { value: 'toasted', label: 'Toasted' }
          ]
        },
        { value: 'cheese', label: 'Cheese' },
        { value: 'chicken', label: 'Grilled Chicken Strips' },
        { value: 'ham', label: 'Ham' },
        { value: 'jalapenos', label: 'Jalapeños' },
        { value: 'lettuce', label: 'Lettuce' },
        { value: 'mushrooms', label: 'Mushrooms' },
        { value: 'olives', label: 'Olives' },
        { value: 'onion', label: 'Onion' },
        { value: 'pepperoni', label: 'Pepperoni' },
        { value: 'pickles', label: 'Pickles' },
        { value: 'salami', label: 'Salami' },
        { value: 'toasted', label: 'Toasted' },
        { value: 'tomatoes', label: 'Tomatoes' },
        { value: 'tuna', label: 'Tuna' },
        { value: 'turkey', label: 'Turkey' }
      ]
    },
    wrap: {
      ingredients: [
        { value: 'bacon', label: 'Bacon' },
        { value: 'bologna', label: 'Bologna' },
        {
          value: 'white',
          label: 'Tortilla',
          required: true,
          noQty: true,
          inputId: 'wrap-bread-checkbox',
          selectId: 'wrap-bread-select',
          selectAriaLabel: 'Choose tortilla',
          options: [
            { value: 'white', label: 'White' },
            { value: 'wheat', label: 'Wheat' },
            { value: 'tomato_basil', label: 'Tomato Basil' },
            { value: 'spinach', label: 'Spinach' }
          ]
        },
        { value: 'cheese', label: 'Cheese' },
        { value: 'ham', label: 'Ham' },
        { value: 'jalapenos', label: 'Jalapeños' },
        { value: 'lettuce', label: 'Lettuce' },
        { value: 'mushrooms', label: 'Mushrooms' },
        { value: 'olives', label: 'Olives' },
        { value: 'onion', label: 'Onion' },
        { value: 'pepperoni', label: 'Pepperoni' },
        { value: 'pickles', label: 'Pickles' },
        { value: 'salami', label: 'Salami' },
        { value: 'tomatoes', label: 'Tomatoes' },
        { value: 'turkey', label: 'Turkey' }
      ]
    }
  },
  ingredientLabels: {
    'pizza_ingredients[]|bacon': 'Bacon',
    'pizza_ingredients[]|boneless_chicken_wings': 'Boneless Chicken Wings',
    'pizza_ingredients[]|broccoli': 'Broccoli',
    'pizza_ingredients[]|chicken': 'Grilled Chicken Strips',
    'pizza_ingredients[]|cheese': 'Cheese',
    'pizza_ingredients[]|regular_dough': 'Dough: Regular (Required)',
    'pizza_ingredients[]|wheat_free_dough': 'Dough: Wheat Free (Required)',
    'pizza_ingredients[]|gluten_free_dough': 'Dough: Gluten Free (Required)',
    'pizza_ingredients[]|garlic': 'Garlic',
    'pizza_ingredients[]|jalapenos': 'Jalapeños',
    'pizza_ingredients[]|lettuce': 'Lettuce',
    'pizza_ingredients[]|meatballs': 'Meatballs',
    'pizza_ingredients[]|mild_sauce': 'Mild sauce',
    'pizza_ingredients[]|mushrooms': 'Mushrooms',
    'pizza_ingredients[]|olives': 'Olives',
    'pizza_ingredients[]|onion': 'Onion',
    'pizza_ingredients[]|pepperoni': 'Pepperoni',
    'pizza_ingredients[]|pickles': 'Pickles',
    'pizza_ingredients[]|pineapple': 'Pineapples',
    'pizza_ingredients[]|ranch': 'Ranch',
    'pizza_ingredients[]|ricotta_cheese': 'Ricotta cheese',
    'pizza_ingredients[]|sausage': 'Sausage',
    'pizza_ingredients[]|thin_crust': 'Thin crust',
    'pizza_ingredients[]|tomatoes': 'Tomatoes',
    'pizza_ingredients[]|tomato_sauce': 'Tomato Sauce (Required)',
    'pizza_ingredients[]|well_done': 'Well-done',

    'burger_ingredients[]|bacon': 'Bacon',
    'burger_ingredients[]|bbq_sauce': 'BBQ Sauce',
    'burger_ingredients[]|bun': 'Bun (Required)',
    'burger_ingredients[]|cheese': 'Cheese',
    'burger_ingredients[]|honey_mustard': 'Honey Mustard',
    'burger_ingredients[]|jalapenos': 'Jalapeños',
    'burger_ingredients[]|ketchup': 'Ketchup',
    'burger_ingredients[]|lettuce': 'Lettuce',
    'burger_ingredients[]|mayonnaise': 'Mayonnaise',
    'burger_ingredients[]|mushrooms': 'Mushrooms',
    'burger_ingredients[]|mild_sauce': 'Mild Sauce',
    'burger_ingredients[]|mustard': 'Mustard',
    'burger_ingredients[]|olives': 'Olives',
    'burger_ingredients[]|onion': 'Onion',
    'burger_ingredients[]|patty': 'Patty (Required)',
    'burger_ingredients[]|pickles': 'Pickles',
    'burger_ingredients[]|ranch': 'Ranch',
    'burger_ingredients[]|relish': 'Relish',
    'burger_ingredients[]|tartar_sauce': 'Tartar Sauce',
    'burger_ingredients[]|tomatoes': 'Tomatoes',
    'burger_ingredients[]|hot_sauce': 'Hot Sauce',
    'burger_ingredients[]|well_done': 'Well-done',
    'burger_ingredients[]|medium_well': 'Medium-well',
    'burger_ingredients[]|rare': 'Rare',

    'calzone_ingredients[]|ricotta_cheese': 'Ricotta cheese',
    'calzone_ingredients[]|regular_dough': 'Dough: Regular (Required)',
    'calzone_ingredients[]|wheat_free_dough': 'Dough: Wheat Free (Required)',
    'calzone_ingredients[]|gluten_free_dough': 'Dough: Gluten Free (Required)',
    'calzone_ingredients[]|shredded_mozzarella': 'Shredded mozzarella',
    'calzone_ingredients[]|grated_parmesan_or_pecorino': 'Grated parmesan or pecorino',
    'calzone_ingredients[]|salt': 'Salt',
    'calzone_ingredients[]|black_pepper': 'Black pepper',
    'calzone_ingredients[]|italian_seasoning': 'Italian seasoning',
    'calzone_ingredients[]|garlic_powder': 'Garlic powder',
    'calzone_ingredients[]|olive_oil': 'Olive oil',
    'calzone_ingredients[]|bacon_bits': 'Bacon bits',
    'calzone_ingredients[]|meatballs': 'Meatballs',
    'calzone_ingredients[]|broccoli': 'Broccoli',
    'calzone_ingredients[]|chicken': 'Grilled Chicken Strips',
    'calzone_ingredients[]|onion': 'Onion',
    'calzone_ingredients[]|steak': 'Steak',
    'calzone_ingredients[]|hot_peppers': 'Hot peppers',
    'calzone_ingredients[]|banana_peppers': 'Banana peppers',
    'calzone_ingredients[]|eggplant': 'Eggplant',
    'calzone_ingredients[]|cheddar_cheese': 'Cheddar cheese',
    'calzone_ingredients[]|feta_cheese': 'Feta cheese',
    'calzone_ingredients[]|greens': 'Greens',
    'calzone_ingredients[]|green_peppers': 'Green peppers',
    'calzone_ingredients[]|jalapenos': 'Jalapeño',
    'calzone_ingredients[]|mushrooms': 'Mushrooms',
    'calzone_ingredients[]|roasted_red_peppers': 'Roasted red peppers',
    'calzone_ingredients[]|pineapple': 'Pineapple',
    'calzone_ingredients[]|spinach': 'Spinach',
    'calzone_ingredients[]|swiss_cheese': 'Swiss cheese',
    'calzone_ingredients[]|american_cheese': 'American cheese',
    'calzone_ingredients[]|tomatoes': 'Tomatoes',
    'calzone_ingredients[]|pepperoni': 'Pepperoni',
    'calzone_ingredients[]|salami': 'Salami',
    'calzone_ingredients[]|sausage': 'Sausage',
    'calzone_ingredients[]|ham': 'Ham',

    'chicken_wings_ingredients[]|garlic': 'Garlic',
    'chicken_wings_ingredients[]|bbq_sauce': 'BBQ sauce',
    'chicken_wings_ingredients[]|butter_sauce': 'Butter sauce',
    'chicken_wings_ingredients[]|hot_sauce': 'Hot sauce',
    'chicken_wings_ingredients[]|medium_sauce': 'Medium sauce',
    'chicken_wings_ingredients[]|plain': 'Plain (Required)',
    'chicken_wings_ingredients[]|extra_hot_sauce': 'Extra hot sauce',
    'chicken_wings_ingredients[]|honey': 'Honey',
    'chicken_wings_ingredients[]|mustard': 'Mustard',
    'chicken_wings_ingredients[]|hot_and_spicy_barbecue_sauce': 'Hot and spicy barbecue sauce',
    'chicken_wings_ingredients[]|mild_sauce': 'Mild sauce',
    'chicken_wings_ingredients[]|spicy_garlic_parm_sauce': 'Spicy garlic parm sauce',

    'salad_ingredients[]|cucumbers': 'Cucumbers',
    'salad_ingredients[]|croutons': 'Croutons',
    'salad_ingredients[]|italian_dressing': 'Italian dressing',
    'salad_ingredients[]|red_onion': 'Red onion',
    'salad_ingredients[]|tomato': 'Tomato',
    'salad_ingredients[]|ham': 'Ham',
    'salad_ingredients[]|olives': 'Olives',
    'salad_ingredients[]|provolone_cheese': 'Provolone cheese',
    'salad_ingredients[]|salami': 'Salami',
    'salad_ingredients[]|banana_peppers': 'Banana peppers',
    'salad_ingredients[]|green_peppers': 'Green peppers',
    'salad_ingredients[]|red_peppers': 'Red peppers',

    'dinner_ingredients[]|baked_ziti': 'Baked Ziti',
    'dinner_ingredients[]|chicken_parmigiana': 'Chicken Parmigiana',
    'dinner_ingredients[]|chicken_riggies': 'Chicken Riggies',
    'dinner_ingredients[]|house_italian_dressing': 'House Italian Dressing',
    'dinner_ingredients[]|lasagna': 'Lasagna',
    'dinner_ingredients[]|manicotti': 'Manicotti',
    'dinner_ingredients[]|spaghetti': 'Spaghetti',
    'dinner_ingredients[]|stuffed_shells': 'Stuffed Shells',
    'dinner_ingredients[]|vodka_riggies': 'Vodka Riggies',

    'sub_ingredients[]|bacon': 'Bacon',
    'sub_ingredients[]|bologna': 'Bologna',
    'sub_ingredients[]|buffalo_sauce': 'Buffalo sauce',
    'sub_ingredients[]|cheese': 'Cheese',
    'sub_ingredients[]|chicken': 'Grilled Chicken Strips',
    'sub_ingredients[]|ham': 'Ham',
    'sub_ingredients[]|jalapenos': 'Jalapeños',
    'sub_ingredients[]|lettuce': 'Lettuce',
    'sub_ingredients[]|mushrooms': 'Mushrooms',
    'sub_ingredients[]|olives': 'Olives',
    'sub_ingredients[]|onion': 'Onion',
    'sub_ingredients[]|pepperoni': 'Pepperoni',
    'sub_ingredients[]|pickles': 'Pickles',
    'sub_ingredients[]|salami': 'Salami',
    'sub_ingredients[]|tomatoes': 'Tomatoes',
    'sub_ingredients[]|toasted': 'Toasted',
    'sub_ingredients[]|white': 'Bread: White (Required)',
    'sub_ingredients[]|tuna': 'Tuna',
    'sub_ingredients[]|wheat': 'Bread: Wheat (Required)',

    'wrap_ingredients[]|bacon': 'Bacon',
    'wrap_ingredients[]|bologna': 'Bologna',
    'wrap_ingredients[]|cheese': 'Cheese',
    'wrap_ingredients[]|ham': 'Ham',
    'wrap_ingredients[]|jalapenos': 'Jalapeños',
    'wrap_ingredients[]|lettuce': 'Lettuce',
    'wrap_ingredients[]|mushrooms': 'Mushrooms',
    'wrap_ingredients[]|olives': 'Olives',
    'wrap_ingredients[]|onion': 'Onion',
    'wrap_ingredients[]|pepperoni': 'Pepperoni',
    'wrap_ingredients[]|pickles': 'Pickles',
    'wrap_ingredients[]|salami': 'Salami',
    'wrap_ingredients[]|tomatoes': 'Tomatoes',
    'wrap_ingredients[]|turkey': 'Turkey',
    'wrap_ingredients[]|white': 'Tortilla: White (Required)',
    'wrap_ingredients[]|wheat': 'Tortilla: Wheat (Required)',
    'wrap_ingredients[]|tomato_basil': 'Tortilla: Tomato Basil',
    'wrap_ingredients[]|spinach': 'Tortilla: Spinach',

    'sauces_ingredients[]|bbq': 'BBQ',
    'sauces_ingredients[]|butter_milk_ranch': 'Butter Milk Ranch',
    'sauces_ingredients[]|honey_bbq': 'Honey BBQ',
    'sauces_ingredients[]|honey_mustard': 'Honey Mustard',
    'sauces_ingredients[]|mayonnaise': 'Mayonnaise',
    'sauces_ingredients[]|mustard': 'Mustard',
    'sauces_ingredients[]|ranch': 'Ranch'
  },
  sectionIngredientCategories: {
    pizza: [
      { id: 'base', label: 'Base', values: ['regular_dough', 'wheat_free_dough', 'gluten_free_dough', 'tomato_sauce'] },
      { id: 'cheese', label: 'Cheese & Toppings', values: ['cheese', 'bacon', 'boneless_chicken_wings', 'broccoli', 'cherry_peppers', 'chicken', 'feta_cheese', 'garlic', 'green_peppers', 'ham', 'jalapenos', 'lettuce', 'meatballs', 'mild_sauce', 'mushrooms', 'olives', 'onion', 'pepperoni', 'pickles', 'pineapple', 'ranch', 'ricotta_cheese', 'roasted_peppers', 'sausage', 'spinach', 'tomatoes'] },
      { id: 'crust', label: 'Crust & Bake', values: ['thin_crust', 'well_done'] }
    ],
    burger: [
      { id: 'protein', label: 'Protein', values: ['patty', 'bacon', 'medium_well', 'rare', 'well_done'] },
      { id: 'sauces', label: 'Sauces', values: ['bbq_sauce', 'honey_mustard', 'hot_sauce', 'ketchup', 'mayonnaise', 'mild_sauce', 'mustard', 'ranch', 'relish', 'tartar_sauce'] },
      { id: 'vegetables', label: 'Vegetables', values: ['lettuce', 'mushrooms', 'olives', 'onion', 'tomatoes', 'pickles', 'jalapenos'] },
      { id: 'base', label: 'Base', values: ['bun', 'cheese'] }
    ],
    calzone: [
      { id: 'base', label: 'Base', values: ['regular_dough', 'wheat_free_dough', 'gluten_free_dough'] },
      { id: 'cheese', label: 'Cheese', values: ['american_cheese', 'cheddar_cheese', 'feta_cheese', 'grated_parmesan_or_pecorino', 'ricotta_cheese', 'shredded_mozzarella', 'swiss_cheese'] },
      { id: 'meats', label: 'Meats', values: ['bacon_bits', 'chicken', 'ham', 'meatballs', 'pepperoni', 'salami', 'sausage', 'steak'] },
      { id: 'veggies', label: 'Vegetables', values: ['banana_peppers', 'broccoli', 'eggplant', 'green_peppers', 'greens', 'hot_peppers', 'jalapenos', 'mushrooms', 'onion', 'pineapple', 'roasted_red_peppers', 'spinach', 'tomatoes'] },
      { id: 'seasonings', label: 'Seasonings', values: ['black_pepper', 'garlic_powder', 'italian_seasoning', 'olive_oil', 'salt'] }
    ],
    chicken_wings: [
      { id: 'sauces', label: 'Sauces', values: ['bbq_sauce', 'butter_sauce', 'hot_and_spicy_barbecue_sauce', 'hot_sauce', 'medium_sauce', 'mild_sauce', 'mustard', 'extra_hot_sauce', 'spicy_garlic_parm_sauce'] },
      { id: 'extras', label: 'Extras', values: ['garlic', 'honey'] },
      { id: 'base', label: 'Base', values: ['plain'] }
    ],
    salad: [
      { id: 'greens', label: 'Greens', values: ['cucumbers', 'green_peppers', 'red_onion', 'red_peppers', 'tomato'] },
      { id: 'protein', label: 'Protein', values: ['ham', 'provolone_cheese', 'salami'] },
      { id: 'extras', label: 'Extras', values: ['banana_peppers', 'croutons', 'olives'] },
      { id: 'dressings', label: 'Dressings', values: ['italian_dressing'] }
    ],
    dinner: [
      { id: 'pasta', label: 'Pasta', values: ['baked_ziti', 'lasagna', 'manicotti', 'spaghetti', 'stuffed_shells', 'vodka_riggies'] },
      { id: 'chicken', label: 'Chicken', values: ['chicken_parmigiana', 'chicken_riggies'] },
      { id: 'dressings', label: 'Dressings', values: ['house_italian_dressing'] }
    ],
    sub: [
      { id: 'bread', label: 'Bread', values: ['white', 'wheat', 'toasted'] },
      { id: 'meat', label: 'Meat', values: ['bacon', 'bologna', 'chicken', 'cheese', 'ham', 'pepperoni', 'salami', 'tuna', 'turkey'] },
      { id: 'veggies', label: 'Vegetables', values: ['jalapenos', 'lettuce', 'mushrooms', 'olives', 'onion', 'pickles', 'tomatoes'] },
      { id: 'extras', label: 'Extras', values: ['buffalo_sauce'] }
    ],
    wrap: [
      { id: 'tortilla', label: 'Tortilla', values: ['white', 'wheat', 'tomato_basil', 'spinach'] },
      { id: 'meat', label: 'Meat', values: ['bacon', 'bologna', 'ham', 'pepperoni', 'salami', 'turkey'] },
      { id: 'extras', label: 'Extras', values: ['cheese', 'jalapenos', 'lettuce', 'mushrooms', 'olives', 'onion', 'pickles', 'tomatoes'] }
    ],
    sauces: [
      { id: 'dressings', label: 'Dressings', values: ['butter_milk_ranch', 'mayonnaise', 'ranch'] },
      { id: 'savory', label: 'Savory', values: ['bbq', 'mustard'] },
      { id: 'sweet_tangy', label: 'Sweet & Tangy', values: ['honey_bbq', 'honey_mustard'] }
    ]
  },
  presetsBySection: {
    burger: [
      { id: 'regular_burger', name: 'Regular Burger', price: '$0', ingredients: ['bun', 'patty', 'cheese', 'lettuce', 'tomatoes'], description: 'Bun, patty, cheese, lettuce, tomatoes' },
      { id: 'deluxe_burger', name: 'Deluxe Burger', price: '$0', ingredients: ['bun', 'patty', 'cheese', 'lettuce', 'tomatoes', 'bacon'], description: 'Bun, patty, cheese, lettuce, tomatoes, bacon' },
      { id: 'veggie_burger', name: 'Vegetable Burger', price: '$0', ingredients: ['bun', 'cheese', 'lettuce', 'tomatoes', 'mushrooms', 'olives'], description: 'Bun, cheese, lettuce, tomatoes, mushrooms, olives' },
      { id: 'double_burger', name: 'Double Burger', price: '$0', ingredients: ['bun', 'patty', 'cheese', 'lettuce', 'tomatoes'], ingredientQty: { patty: '3' }, description: 'Bun, double patty, cheese, lettuce, tomatoes' },
      { id: 'triple_burger', name: 'Triple Burger', price: '$0', ingredients: ['bun', 'patty', 'cheese', 'lettuce', 'tomatoes'], ingredientQty: { patty: '4' }, description: 'Bun, triple patty, cheese, lettuce, tomatoes' }
    ],
    calzone: [
      { id: 'meat_calzone', name: 'Meaty Calzone', price: '$0', ingredients: ['american_cheese', 'ham', 'pepperoni', 'meatballs'], description: 'American cheese, ham, pepperoni, meatballs' },
      { id: 'garden_calzone', name: 'Garden Calzone', price: '$0', ingredients: ['broccoli', 'eggplant', 'spinach', 'onion', 'tomatoes'], description: 'Broccoli, eggplant, spinach, onion, tomatoes' },
      { id: 'lasagna_calzone', name: 'Lasagna Calzone', price: '$0', ingredients: ['meatballs', 'shredded_mozzarella', 'ricotta_cheese', 'sausage'], description: 'Meatballs, shredded mozzarella, ricotta cheese, sausage' },
      { id: 'chicken_wing_calzone', name: 'Chicken Wing Calzone', price: '$0', ingredients: ['chicken', 'shredded_mozzarella'], description: 'Chicken, shredded mozzarella' },
      { id: 'everything_calzone', name: 'Everything Calzone', price: '$0', ingredients: ['green_peppers', 'shredded_mozzarella', 'mushrooms', 'pepperoni', 'sausage'], description: 'Green peppers, shredded mozzarella, mushrooms, pepperoni, sausage' }
    ],
    chicken_wings: [
      { id: 'everything_wings', name: 'Everything Wings', price: '$0', ingredients: ['plain', 'bbq_sauce', 'butter_sauce', 'extra_hot_sauce', 'garlic', 'honey', 'hot_and_spicy_barbecue_sauce', 'hot_sauce', 'medium_sauce', 'mild_sauce', 'mustard', 'spicy_garlic_parm_sauce'], description: 'Plain wings with all sauces and extras' },
      { id: 'bbq_wings', name: 'BBQ Wings', price: '$0', ingredients: ['plain', 'bbq_sauce'], description: 'Plain wings with BBQ sauce' },
      { id: 'hot_spicy_bbq_wings', name: 'Hot and Spicy BBQ Wings', price: '$0', ingredients: ['plain', 'hot_and_spicy_barbecue_sauce'], description: 'Plain wings with hot and spicy barbecue sauce' },
      { id: 'hot_wings', name: 'Hot Wings', price: '$0', ingredients: ['plain', 'hot_sauce'], description: 'Plain wings with hot sauce' },
      { id: 'extra_hot_wings', name: 'Extra Hot Wings', price: '$0', ingredients: ['plain', 'extra_hot_sauce'], description: 'Plain wings with extra hot sauce' },
      { id: 'medium_wings', name: 'Medium Wings', price: '$0', ingredients: ['plain', 'medium_sauce'], description: 'Plain wings with medium sauce' },
      { id: 'mild_wings', name: 'Mild Wings', price: '$0', ingredients: ['plain', 'mild_sauce'], description: 'Plain wings with mild sauce' }
    ],
    salad: [
      { id: 'classic_salad', name: 'Classic Salad', price: '$0', ingredients: ['lettuce', 'tomato', 'cucumbers', 'italian_dressing'], description: 'Lettuce, tomato, cucumbers, Italian dressing' },
      { id: 'protein_salad', name: 'Protein Salad', price: '$0', ingredients: ['lettuce', 'tomato', 'ham', 'salami', 'provolone_cheese'], description: 'Lettuce, tomato, ham, salami, provolone cheese' },
      { id: 'antipasto_salad', name: 'Antipasto Salad', price: '$0', ingredients: ['banana_peppers', 'cucumbers', 'ham', 'italian_dressing', 'olives', 'provolone_cheese', 'red_onion', 'red_peppers', 'salami', 'tomato'], description: 'Ham, salami, provolone cheese, olives, banana peppers, red onion, red peppers, tomato, cucumbers, Italian dressing' }
    ],
    sauces: [
      { id: 'bbq_combo', name: 'BBQ Combo', price: '$0', ingredients: ['bbq', 'honey_mustard'], description: 'BBQ, honey mustard' },
      { id: 'ranch_combo', name: 'Ranch Combo', price: '$0', ingredients: ['ranch', 'mayonnaise'], description: 'Ranch, mayonnaise' }
    ],
    sub: [
      { id: 'italian_sub', name: 'Italian Sub', price: '$0', ingredients: ['white', 'salami', 'ham', 'cheese', 'lettuce', 'tomatoes'], description: 'White bread, salami, ham, cheese, lettuce, tomatoes' },
      { id: 'chicken_sub', name: 'Chicken Sub', price: '$0', ingredients: ['white', 'chicken', 'cheese', 'lettuce', 'tomatoes'], description: 'White bread, chicken, cheese, lettuce, tomatoes' },
      { id: 'buffalo_chicken_sub', name: 'Buffalo Chicken Sub', price: '$0', ingredients: ['white', 'chicken', 'buffalo_sauce', 'cheese', 'lettuce'], description: 'White bread, chicken, buffalo sauce, cheese, lettuce' },
      { id: 'salami_sub', name: 'Salami', price: '$0', ingredients: ['white', 'salami', 'cheese', 'lettuce', 'tomatoes'], description: 'White bread, salami, cheese, lettuce, tomatoes' },
      { id: 'tuna_sub', name: 'Tuna', price: '$0', ingredients: ['white', 'tuna', 'lettuce', 'tomatoes'], description: 'White bread, tuna, lettuce, tomatoes' },
      { id: 'ham_cheese_sub', name: 'Ham & Cheese', price: '$0', ingredients: ['white', 'ham', 'cheese', 'lettuce', 'tomatoes'], description: 'White bread, ham, cheese, lettuce, tomatoes' },
      { id: 'turkey_sub', name: 'Turkey Sub', price: '$0', ingredients: ['white', 'turkey', 'lettuce', 'onion', 'tomatoes'], description: 'White bread, turkey, lettuce, onion, tomatoes' },
      { id: 'mixed_sub', name: 'Mixed', price: '$0', ingredients: ['white', 'bologna', 'ham', 'salami', 'cheese', 'lettuce', 'tomatoes'], description: 'White bread, bologna, ham, salami, cheese, lettuce, tomatoes' },
      { id: 'blt_sub', name: 'BLT', price: '$0', ingredients: ['white', 'bacon', 'lettuce', 'tomatoes'], description: 'White bread, bacon, lettuce, tomatoes' },
      { id: 'veggie_sub', name: 'Veggie', price: '$0', ingredients: ['white', 'cheese', 'lettuce', 'mushrooms', 'olives', 'onion', 'pickles', 'tomatoes'], description: 'White bread, cheese, lettuce, mushrooms, olives, onion, pickles, tomatoes' }
    ],
    wrap: [
      { id: 'chicken_wrap', name: 'Chicken Wrap', price: '$0', ingredients: ['white', 'turkey', 'lettuce', 'cheese', 'tomatoes'], description: 'Tortilla, turkey, lettuce, cheese, tomatoes' },
      { id: 'veggie_wrap', name: 'Veggie Wrap', price: '$0', ingredients: ['spinach', 'lettuce', 'mushrooms', 'olives', 'tomatoes'], description: 'Spinach tortilla, lettuce, mushrooms, olives, tomatoes' }
    ],
    pizza: [
      { id: 'cheese_pizza', name: 'Cheese Pizza', price: '$0', ingredients: ['cheese', 'tomato_sauce'], description: 'Cheese, tomato sauce' },
      { id: 'hawaiian_pizza', name: 'Hawaiian Pizza', price: '$0', ingredients: ['ham', 'cheese', 'pineapple', 'tomato_sauce'], description: 'Ham, cheese, pineapple, tomato sauce' },
      { id: 'garlic_pizza', name: 'Garlic Pizza', price: '$0', ingredients: ['cheese', 'garlic', 'tomato_sauce'], description: 'Cheese, garlic, tomato sauce' },
      { id: 'lasagna_pizza', name: 'Lasagna Pizza', price: '$0', ingredients: ['meatballs', 'cheese', 'tomato_sauce', 'ricotta_cheese', 'sausage'], description: 'Meatballs, cheese, tomato sauce, ricotta cheese, sausage' },
      { id: 'pepperoni_pizza', name: 'Pepperoni Pizza', price: '$0', ingredients: ['cheese', 'pepperoni', 'tomato_sauce'], description: 'Cheese, pepperoni, tomato sauce' },
      { id: 'chicken_bacon_ranch_pizza', name: 'chicken Bacon Ranch Pizza', price: '$0', ingredients: ['bacon', 'chicken', 'cheese', 'ranch'], description: 'Bacon, chicken, cheese, ranch' },
      { id: 'vegetarian_pizza', name: 'Vegetarian Pizza', price: '$0', ingredients: ['broccoli', 'green_peppers', 'cheese', 'mushrooms', 'onion', 'tomato_sauce'], description: 'Broccoli, green peppers, cheese, mushrooms, onion, tomato sauce' },
      { id: 'supreme_pizza', name: 'Supreme Pizza', price: '$0', ingredients: ['cheese', 'pepperoni', 'green_peppers', 'mushrooms', 'onion', 'tomato_sauce'], description: 'Cheese, pepperoni, green peppers, mushrooms, onion, tomato sauce' },
      { id: 'stuffed_pizza', name: 'Stuffed Pizza', price: '$0', ingredients: ['green_peppers', 'cheese', 'mushrooms', 'pepperoni', 'tomato_sauce', 'sausage'], description: 'Green peppers, cheese, mushrooms, pepperoni, tomato sauce, sausage' },
      { id: 'chicken_wing_pizza', name: 'chicken Wing Pizza', price: '$0', ingredients: ['boneless_chicken_wings', 'mild_sauce', 'cheese', 'ranch'], description: 'Boneless chicken wings, mild sauce, cheese, ranch' }
    ],
    dinner: [
      { id: 'manicotti_dinner', name: 'Manicotti', price: '$0', ingredients: ['manicotti', 'house_italian_dressing'], description: 'Manicotti, house Italian dressing' },
      { id: 'stuffed_shells_dinner', name: 'Stuffed Shells', price: '$0', ingredients: ['stuffed_shells', 'house_italian_dressing'], description: 'Stuffed shells, house Italian dressing' },
      { id: 'baked_ziti_dinner', name: 'Baked Ziti', price: '$0', ingredients: ['baked_ziti', 'house_italian_dressing'], description: 'Baked ziti, house Italian dressing' },
      { id: 'spaghetti_dinner', name: 'Spaghetti', price: '$0', ingredients: ['spaghetti', 'house_italian_dressing'], description: 'Spaghetti, house Italian dressing' },
      { id: 'lasagna_dinner', name: 'Lasagna', price: '$0', ingredients: ['lasagna', 'house_italian_dressing'], description: 'Lasagna, house Italian dressing' },
      { id: 'chicken_parmigiana_dinner', name: 'Chicken Parmigiana', price: '$0', ingredients: ['chicken_parmigiana', 'house_italian_dressing'], description: 'Chicken Parmigiana, house Italian dressing' },
      { id: 'chicken_riggies_dinner', name: 'Chicken Riggies', price: '$0', ingredients: ['chicken_riggies', 'house_italian_dressing'], description: 'Chicken riggies, house Italian dressing' },
      { id: 'vodka_riggies_dinner', name: 'Vodka Riggies', price: '$0', ingredients: ['vodka_riggies', 'house_italian_dressing'], description: 'Vodka riggies, house Italian dressing' }
    ]
  }
};
